const B=[
["classic-350","Royal Enfield","Classic 350",1.93,349,"35 kmpl","Petrol","5-speed","20.2 PS @ 6100 rpm","27 Nm @ 4000 rpm",114,"195 kg","13 L","300mm disc front, 270mm rear, dual-channel ABS","19in front / 18in rear, tubeless","Telescopic fork / twin shock absorbers",["Halcyon Black","Signals Green","Chrome Bronze"],["Timeless retro styling","Thumpy, relaxed engine","Comfortable seat"],95],
["hunter-350","Royal Enfield","Hunter 350",1.50,349,"36 kmpl","Petrol","5-speed","20.2 PS @ 6100 rpm","27 Nm @ 4000 rpm",114,"181 kg","13 L","300mm disc front, 270mm rear, dual-channel ABS","17in alloy wheels, tubeless","Telescopic fork / twin shock absorbers",["Factory Black","Rebel Red","Dapper Grey"],["Lightest 350 RE","Agile city handling","Affordable price"],92],
["mt-15","Yamaha","MT-15 V2",1.69,155,"56 kmpl","Petrol","6-speed","18.4 PS @ 10000 rpm","14.1 Nm @ 7500 rpm",125,"141 kg","10 L","282mm disc front, 220mm rear, dual ABS","17in alloy, 100/80 front, 140/70 rear","USD fork / monoshock",["Cyan Storm","Metallic Black","Ice Fluo-Vermillion"],["Aggressive naked look","VVA engine","Light and agile"],90],
["r15","Yamaha","R15 V4",1.82,155,"55 kmpl","Petrol","6-speed","18.4 PS @ 10000 rpm","14.2 Nm @ 7500 rpm",140,"141 kg","11 L","282mm disc front, 220mm rear, dual ABS","17in alloy, 100/80 front, 140/70 rear","USD fork / linked monoshock",["Racing Blue","Metallic Red","Dark Knight"],["Supersport design","Quickshifter option","Traction control"],93],
["duke-390","KTM","Duke 390",3.10,399,"28 kmpl","Petrol","6-speed","46 PS @ 8500 rpm","39 Nm @ 6500 rpm",167,"171 kg","13.4 L","320mm disc front, 240mm rear, cornering ABS","17in alloy, 110/70 front, 150/60 rear","WP APEX USD fork / monoshock",["Electronic Orange","Metallic Silver","Dark Galvano"],["Powerful 399cc engine","TFT display","Ride modes"],88],
["rc-390","KTM","RC 390",3.19,399,"27 kmpl","Petrol","6-speed","46 PS @ 9000 rpm","39 Nm @ 7000 rpm",175,"172 kg","13.7 L","320mm disc front, 230mm rear, cornering ABS","17in alloy, 110/70 front, 150/60 rear","WP APEX USD fork / monoshock",["Orange","White","Black"],["Track-bred fairing","Quickshifter","Launch control"],82],
["cb350","Honda","CB350",2.10,348,"35 kmpl","Petrol","5-speed","21 PS @ 5500 rpm","30 Nm @ 3000 rpm",130,"179 kg","15 L","310mm disc front, 240mm rear, dual ABS","19in front / 18in rear","Telescopic fork / twin shock absorbers",["Pearl Igneous Black","Athletic Blue","Precious Red"],["Smooth refined engine","HSTC traction control","Premium build"],80],
["apache-310","TVS","Apache RTR 310",2.40,312,"30 kmpl","Petrol","6-speed","35.6 PS @ 9700 rpm","28.7 Nm @ 6650 rpm",150,"169 kg","11 L","300mm disc front, 240mm rear, dual ABS","17in alloy, 110/70 front, 150/60 rear","USD fork / monoshock",["Fury Yellow","Tarmac Black","Red"],["Feature-loaded","Ride modes","Great value performance"],85],
["ns200","Bajaj","Pulsar NS200",1.55,199.5,"36 kmpl","Petrol","6-speed","24.5 PS @ 9750 rpm","18.74 Nm @ 8000 rpm",136,"159 kg","12 L","280mm disc front, 230mm rear, dual ABS","17in alloy, 100/80 front, 130/70 rear","Telescopic fork / Nitrox monoshock",["Pearl White","Pewter Grey","Burnt Red"],["Strong mid-range","Sharp handling","Value for money"],87],
["xtreme-160r","Hero","Xtreme 160R 4V",1.30,163,"55 kmpl","Petrol","5-speed","16.9 PS @ 8500 rpm","14.6 Nm @ 6500 rpm",117,"145 kg","12 L","276mm disc front, 220mm rear, ABS","17in alloy, 80/100 front, 130/70 rear","Telescopic fork / monoshock",["Cherry Red","Matte Black","Blue"],["Lightweight","Great mileage","Low running cost"],75],
["gixxer-sf-250","Suzuki","Gixxer SF 250",1.95,249,"38 kmpl","Petrol","6-speed","26.5 PS @ 9300 rpm","22.2 Nm @ 7300 rpm",145,"161 kg","12 L","300mm disc front, 220mm rear, dual ABS","17in alloy, 100/80 front, 140/70 rear","Telescopic fork / monoshock",["Metallic Blue","Metallic Black","Silver"],["Oil-cooled smooth engine","Fully faired comfort","Reliable"],70]
].map(a=>({id:a[0],brand:a[1],name:a[2],price:a[3],cc:a[4],mil:a[5],fuel:a[6],tr:a[7],pw:a[8],tq:a[9],top:a[10],wt:a[11],tank:a[12],br:a[13],ty:a[14],su:a[15],col:a[16],pros:a[17],pop:a[18]}));
const BR=["Royal Enfield","Yamaha","KTM","Honda","Bajaj","TVS","Hero","Suzuki"];
const T=(p,r)=>({p,r});
const BL=[
["top5-under-2-lakh","Top 5 Bikes Under ₹2 Lakh in 2026","Buying Guides","Rahul Mehta","12 Jan 2026",6,"Great value picks for budget buyers.",["If your budget is under ₹2 lakh, you have excellent choices across commuter, naked and retro segments.","The Hunter 350, Pulsar NS200, MT-15, Xtreme 160R and R15 balance performance, mileage and running costs well.","Check the table below and book a test ride to feel the difference."],["hunter-350","ns200","mt-15","xtreme-160r","r15"]],
["classic-350-review","Royal Enfield Classic 350 Complete Review","Bike Reviews","Aman Verma","20 Jan 2026",8,"Retro charm with modern refinement.",["The Classic 350 uses the J-series 349cc engine that is smoother than the older generation.","It delivers relaxed highway cruising, a comfortable seat and a strong road presence.","The trade-offs are weight and a modest top speed, but for character it is hard to beat."],["classic-350"]],
["best-college-bikes","Best Bikes for College Students","Buying Guides","Sneha Kulkarni","02 Feb 2026",5,"Affordable, efficient and stylish.",["Students need low running costs, easy handling and good looks.","The Xtreme 160R, NS200 and MT-15 are light, efficient and easy to ride in traffic.","Consider insurance, service cost and resale value before buying."],["xtreme-160r","ns200","mt-15"]],
["maintain-motorcycle","How to Maintain Your Motorcycle","Maintenance","Karan Joshi","15 Feb 2026",7,"Simple habits that extend bike life.",["Change engine oil and filter as per the service schedule, usually every 3,000-5,000 km.","Check tyre pressure weekly, lubricate and adjust the chain every 500 km, and inspect brake pads regularly.","Keep the battery charged, wash gently and always service at an authorised centre."],[]],
["duke-390-vs-mt-15","KTM Duke 390 vs Yamaha MT-15","Comparisons","Rahul Mehta","01 Mar 2026",6,"Power versus lightweight fun.",["The Duke 390 offers far more power and features, while the MT-15 wins on price, mileage and running cost.","Choose the Duke for highway speed and performance; choose the MT-15 for daily city use.","Compare the specs below."],["duke-390","mt-15"]],
["best-mileage-bikes","Best Mileage Bikes in India","Buying Guides","Aman Verma","12 Mar 2026",5,"Save fuel without losing fun.",["Mileage matters for daily commuters. 155-165cc bikes give the best balance of efficiency and performance.","The MT-15, R15 and Xtreme 160R lead our list with 55+ kmpl claimed figures.","Real-world mileage depends on riding style and maintenance."],["mt-15","r15","xtreme-160r"]],
["used-bike-checklist","Things to Check Before Buying a Used Bike","Buying Guides","Sneha Kulkarni","25 Mar 2026",7,"Avoid costly mistakes.",["Verify RC, insurance, service history and chassis/engine numbers match the papers.","Inspect for leaks, frame damage, tyre wear, chain condition and unusual engine noise.","Always take a test ride and, if possible, a mechanic along."],[]],
["upcoming-2026","Upcoming Motorcycles to Watch in 2026","New Bike Launches","Karan Joshi","05 Apr 2026",6,"New launches riders are waiting for.",["2026 is expected to bring more mid-capacity bikes, new electric options and updated flagship models.","Keep an eye on 350-450cc retro roadsters and new performance nakeds.","Launch details can change, so follow our news section for confirmed dates."],[]]
].map(a=>({id:a[0],title:a[1],cat:a[2],au:a[3],date:a[4],min:a[5],desc:a[6],body:a[7],bikes:a[8],img:a[0]}));
const $=(s,e=document)=>e.querySelector(s),$$=(s,e=document)=>[...e.querySelectorAll(s)];
const q=k=>new URLSearchParams(location.search).get(k);
const price=b=>"₹"+b.price.toFixed(2)+" Lakh";
const ls=(k,v)=>{try{if(v===undefined)return JSON.parse(localStorage.getItem(k)||"[]");localStorage.setItem(k,JSON.stringify(v))}catch(e){return[]}};
function ph(n){const s=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 400"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="#26262c"/><stop offset="1" stop-color="#0b0b0d"/></linearGradient></defs><rect width="640" height="400" fill="url(#g)"/><g fill="none" stroke="#e10600" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"><circle cx="190" cy="250" r="62"/><circle cx="450" cy="250" r="62"/><path d="M190 250L260 170H340L450 250M340 170L300 250H190M260 170L235 140H275M340 170L395 150L430 170"/></g><text x="320" y="360" fill="#fff" font-family="Arial" font-size="26" font-weight="bold" text-anchor="middle">${n}</text></svg>`;return "data:image/svg+xml,"+encodeURIComponent(s)}
const im=(slug,n,cls="")=>`<img class="${cls}" src="images/${slug}.jpg" alt="${n}" loading="lazy" onerror="this.onerror=null;this.src=ph('${n.replace(/'/g,"")}')">`;
const bimg=(b,i=0)=>im(i?b.id+"-"+i:b.id,b.brand+" "+b.name);
const card=b=>`<article class="card glass rv"><button class="fav ${ls("fav").includes(b.id)?"on":""}" data-fav="${b.id}" aria-label="Wishlist">&#9829;</button><a class="im" href="bike-details.html?id=${b.id}">${bimg(b)}</a><div class="cb"><small>${b.brand}</small><h3>${b.name}</h3><div class="pr">${price(b)}</div><ul class="sp"><li>&#9881; ${b.cc} cc</li><li>&#9981; ${b.mil}</li><li>&#128738; ${b.fuel}</li><li>&#9965; ${b.tr}</li></ul><div class="btns"><a class="btn sm" href="bike-details.html?id=${b.id}">View Details</a><button class="btn sm ghost" data-cmp="${b.id}">Compare</button><a class="btn sm red" href="test-drive.html?bike=${b.id}">Book Test Ride</a></div></div></article>`;
const bcard=p=>`<article class="card glass rv"><a class="im" href="blog-details.html?id=${p.id}">${im("blog-"+p.id,p.title)}</a><div class="cb"><small>${p.cat}</small><h3>${p.title}</h3><p>${p.desc}</p><p class="meta">${p.au} · ${p.date}</p><a class="btn sm red" href="blog-details.html?id=${p.id}">Read More</a></div></article>`;
const page=document.body.dataset.page;
function reveal(){const o=new IntersectionObserver(e=>e.forEach(x=>{if(x.isIntersecting){x.target.classList.add("in");o.unobserve(x.target)}}),{threshold:.1});$$(".rv:not(.in)").forEach(e=>o.observe(e))}
document.addEventListener("click",e=>{const f=e.target.closest("[data-fav]");if(f){let a=ls("fav");const i=f.dataset.fav;a=a.includes(i)?a.filter(x=>x!==i):[...a,i];ls("fav",a);$$(`[data-fav="${i}"]`).forEach(x=>x.classList.toggle("on"))}
const c=e.target.closest("[data-cmp]");if(c){let a=ls("cmp").filter(x=>x!==c.dataset.cmp);a.push(c.dataset.cmp);ls("cmp",a.slice(-3));location.href="compare.html"}});
/* common UI */
const th=(()=>{try{return localStorage.getItem("theme")||"dark"}catch(e){return"dark"}})();document.documentElement.dataset.t=th;
$("#theme").onclick=()=>{const t=document.documentElement.dataset.t==="dark"?"light":"dark";document.documentElement.dataset.t=t;try{localStorage.setItem("theme",t)}catch(e){}};
$("#burger").onclick=()=>$("#nv").classList.toggle("on");
const so=$("#so"),si=$("#si");$("#sbtn").onclick=()=>{so.classList.add("on");si.focus()};$("#sx").onclick=()=>so.classList.remove("on");
si.oninput=()=>{const t=si.value.trim().toLowerCase();if(t.length<2){$("#sr").innerHTML="";return}let h="";
B.filter(b=>[b.brand,b.name,b.cc+"cc",b.pw,b.tq,b.mil,b.tr,b.fuel,b.br].join(" ").toLowerCase().includes(t)).forEach(b=>h+=`<a href="bike-details.html?id=${b.id}">&#127949; ${b.brand} ${b.name}<br><small>${b.cc}cc · ${b.pw} · ${b.mil} · ${price(b)}</small></a>`);
BR.filter(b=>b.toLowerCase().includes(t)).forEach(b=>h+=`<a href="bikes.html?brand=${encodeURIComponent(b)}">&#127970; Brand: ${b}</a>`);
BL.filter(p=>(p.title+p.cat+p.desc+p.body.join(" ")).toLowerCase().includes(t)).forEach(p=>h+=`<a href="blog-details.html?id=${p.id}">&#128240; ${p.title}<br><small>${p.cat}</small></a>`);
$("#sr").innerHTML=h||"<p class='meta'>No results found.</p>"};
const tp=$("#top");addEventListener("scroll",()=>tp.classList.toggle("on",scrollY>400));tp.onclick=()=>scrollTo({top:0});
addEventListener("load",()=>setTimeout(()=>$("#loader").classList.add("off"),300));
function counters(){$$("[data-count]").forEach(el=>{const n=+el.dataset.count;let i=0;const s=Math.max(1,Math.ceil(n/60));const t=setInterval(()=>{i=Math.min(n,i+s);el.textContent=i+(n>100?"+":"");if(i>=n)clearInterval(t)},25)})}
/* pages */
if(page==="index.html"){$("#featured").innerHTML=B.slice(0,6).map(card).join("");$("#latest").innerHTML=BL.slice(0,3).map(bcard).join("");
$("#brandGrid").innerHTML=BR.map(b=>`<a class="bt glass" href="bikes.html?brand=${encodeURIComponent(b)}">${b.toUpperCase()}<small>${B.filter(x=>x.brand===b).length} bike(s)</small></a>`).join("");counters()}
if(page==="bikes.html"){$("#fb").innerHTML='<option value="">All brands</option>'+BR.map(b=>`<option>${b}</option>`).join("");if(q("brand"))$("#fb").value=q("brand");
const run=()=>{const rg=v=>v?v.split("-").map(Number):[0,1e9];const[p0,p1]=rg($("#fp").value),[c0,c1]=rg($("#fc").value);
let l=B.filter(b=>(!$("#fb").value||b.brand===$("#fb").value)&&b.price>=p0&&b.price<p1&&b.cc>=c0&&b.cc<c1&&(!$("#ff").value||b.fuel===$("#ff").value));
const s=$("#fs").value;l.sort((a,b)=>s==="lo"?a.price-b.price:s==="hi"?b.price-a.price:b.pop-a.pop);
$("#list").innerHTML=l.map(card).join("");$("#none").hidden=l.length>0;reveal()};
$$(".filters select").forEach(s=>s.onchange=run);run()}
if(page==="bike-details.html"){const b=B.find(x=>x.id===q("id"))||B[0];document.title=b.brand+" "+b.name+" | MotoDrive Bikes";$("#crumbEnd").innerHTML=`<a href="bikes.html">Bikes</a> / ${b.name}`;
const rows=[["Engine",b.cc+" cc, "+b.fuel],["Power",b.pw],["Torque",b.tq],["Mileage",b.mil],["Top speed",b.top+" km/h"],["Kerb weight",b.wt],["Fuel tank",b.tank],["Brakes",b.br],["Tyres",b.ty],["Suspension",b.su],["Transmission",b.tr],["Colours",b.col.join(", ")]];
$("#detail").innerHTML=`<div class="dt"><div class="gal"><div class="big" id="big">${bimg(b)}</div><div class="th">${[0,1,2].map(i=>im(i?b.id+"-"+i:b.id,b.brand+" "+b.name+(i?" view "+(i+1):"")).replace("<img",`<img data-i="${i}"`)).join("")}</div></div>
<div><small style="color:var(--red);font-weight:700">${b.brand.toUpperCase()}</small><h1>${b.name}</h1><div class="pr" style="font-size:1.6rem">${price(b)} <small class="meta">ex-showroom (approx.)</small></div>
<div class="tw"><table>${rows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td></tr>`).join("")}</table></div><h3>Pros &amp; Features</h3><ul class="pros">${b.pros.map(p=>`<li>${p}</li>`).join("")}</ul>
<div class="btns"><a class="btn red" href="test-drive.html?bike=${b.id}">Book Test Ride</a><button class="btn" data-cmp="${b.id}">Compare</button><button class="btn ghost" data-fav="${b.id}">&#9829; Wishlist</button></div></div></div>`;
$$(".th img").forEach(t=>t.onclick=()=>{$("#big").innerHTML=t.outerHTML.replace('class="','class="x ');$$(".th img").forEach(x=>x.classList.remove("on"));t.classList.add("on")})}
if(page==="compare.html"){const st=ls("cmp");[0,1,2].forEach(i=>{const s=$("#c"+i);s.innerHTML=`<option value="">${i<2?"Select bike "+(i+1):"Add third bike (optional)"}</option>`+B.map(b=>`<option value="${b.id}">${b.brand} ${b.name}</option>`).join("");s.value=st[i]||"";s.onchange=draw});
function draw(){const sel=[0,1,2].map(i=>B.find(b=>b.id===$("#c"+i).value)).filter(Boolean);ls("cmp",sel.map(b=>b.id));
if(sel.length<2){$("#ct").innerHTML='<p class="c">Choose at least two bikes.</p>';return}
const R=[["Price",b=>price(b)],["Engine",b=>b.cc+" cc"],["Power",b=>b.pw],["Torque",b=>b.tq],["Mileage",b=>b.mil],["Weight",b=>b.wt],["Fuel tank",b=>b.tank],["Brakes",b=>b.br],["Top speed",b=>b.top+" km/h"],["Key features",b=>b.pros.join(", ")]];
$("#ct").innerHTML=`<table><tr><th></th>${sel.map(b=>`<th>${b.brand} ${b.name}</th>`).join("")}</tr><tr><td></td>${sel.map(b=>`<td>${bimg(b)}</td>`).join("")}</tr>${R.map(r=>`<tr><td>${r[0]}</td>${sel.map(b=>`<td>${r[1](b)}</td>`).join("")}</tr>`).join("")}</table>`}draw()}
if(page==="blog.html"){const cats=["All","Bike Reviews","New Bike Launches","Buying Guides","Maintenance","Riding Tips","Comparisons","Motorcycle News","Accessories"];
$("#chips").innerHTML=cats.map((c,i)=>`<button class="chip ${i?"":"on"}">${c}</button>`).join("");
const show=c=>{const l=BL.filter(p=>c==="All"||p.cat===c);$("#blogs").innerHTML=l.length?l.map(bcard).join(""):"<p class='meta'>No articles in this category yet.</p>";reveal()};
$$(".chip").forEach(b=>b.onclick=()=>{$$(".chip").forEach(x=>x.classList.remove("on"));b.classList.add("on");show(b.textContent)});show("All")}
if(page==="blog-details.html"){const p=BL.find(x=>x.id===q("id"))||BL[0];document.title=p.title+" | MotoDrive Bikes";$("#crumbEnd").innerHTML=`<a href="blog.html">Blog</a> / ${p.title}`;
const bs=p.bikes.map(i=>B.find(b=>b.id===i)),u=encodeURIComponent(location.href),tt=encodeURIComponent(p.title);
$("#article").innerHTML=`<small style="color:var(--red);font-weight:700">${p.cat}</small><h1>${p.title}</h1><p class="meta">By ${p.au} · ${p.date} · ${p.min} min read</p>${im("blog-"+p.id,p.title,"hf")}${p.body.map(x=>`<p>${x}</p>`).join("")}
${bs.length?`<div class="tw"><table><tr><th>Bike</th><th>Price</th><th>Engine</th><th>Mileage</th><th>Power</th></tr>${bs.map(b=>`<tr><td><a href="bike-details.html?id=${b.id}">${b.brand} ${b.name}</a></td><td>${price(b)}</td><td>${b.cc} cc</td><td>${b.mil}</td><td>${b.pw}</td></tr>`).join("")}</table></div>`:""}
<div class="share"><span>Share:</span><a target="_blank" rel="noopener" href="https://wa.me/?text=${tt}%20${u}">WhatsApp</a><a target="_blank" rel="noopener" href="https://twitter.com/intent/tweet?text=${tt}&url=${u}">X</a><a target="_blank" rel="noopener" href="https://www.facebook.com/sharer/sharer.php?u=${u}">Facebook</a></div>`;
$("#related").innerHTML=BL.filter(x=>x.id!==p.id).slice(0,3).map(bcard).join("")}
if(page==="test-drive.html"){$("#tb").innerHTML='<option value="">Choose a bike</option>'+B.map(b=>`<option value="${b.id}">${b.brand} ${b.name}</option>`).join("");if(q("bike"))$("#tb").value=q("bike");
const d=new Date().toISOString().slice(0,10);$("#td").min=d;
$("#tf").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),b=B.find(x=>x.id===f.get("b"));
$("#ok").innerHTML=`<h2>&#10004; Booking Confirmed!</h2><p>Thank you, <b>${f.get("n")}</b>. Your test ride for the <b>${b.brand} ${b.name}</b> is booked for <b>${f.get("d")}</b> at <b>${f.get("t")}</b> in ${f.get("c")}.</p><p class="meta">Confirmation will be sent to ${f.get("e")}. Please carry your driving licence. Ref: MD${Date.now().toString().slice(-6)}</p>`;
$("#ok").hidden=false;e.target.hidden=true;scrollTo({top:0,behavior:"smooth"})}}
if(page==="contact.html"){$("#cf").onsubmit=e=>{e.preventDefault();$("#cok").hidden=false;e.target.reset()}}
reveal();
